services:
  - type: web
    name: fillit-server
    runtime: docker
    dockerfilePath: ./apps/server/Dockerfile
    dockerContext: .
    region: frankfurt
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
